name: Lint the code and create pull request

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master
      - '!main'     # excludes main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-lint:
    if: ${{ !contains(github.actor, 'classroom') }}
    name: Lint the Code which is committed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
