name: Copy Issues from another repository

on:
  workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  create-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: main
          title: Patches
