name: Create pull request manually
on:
  workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  create-pull:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr create -B main -H develop --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

