name: Create pull request manually
on:
  push

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  create-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        run: |
          gh pr create -B main --title "My pull request" --body "Description"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

